<link rel="stylesheet" property='stylesheet' href="http://142.31.53.22/~mdtalks/headerStyle.css" >
<div id='space'></div>
<div id='footerBar'>
	<div id='footerContent'>
		&copy; MD talks, 2015 - <a href="mailto:mountdougtalks@gmail.com?Subject=Info%20About%20Mount%20Doug%20Talks">Contact Us: mountdougtalks@gmail.com</a> - <a href="http://142.31.53.22/~mdtalks/terms.php" >Terms of Use</a>.
	</div>
</div>